return {  
         "Fiquem atentos e não atrapalhem as instruções, pois será essencial que vocês aprendam tudo o que for dito.",
    "Regras Básicas:",
    "I-) É estritamente proibido ser de outro órgão militar brasileiro, pois é considerado traição;",
    "II-) Proibido desrespeitar qualquer militar, sendo subalterno ou superior;",
    "III-) Utilize gramática: pontuações, acentuações, letra maiúscula e minúscula;",
    "IV-) É proibido abreviar as palavras (ex: blz, tmj...);",
    "V-) Gírias que não sejam militares são proibidas (ex: suave, firmeza...);",
    "VI-) A disciplina é obrigatória em nossa instituição;",
    "VII-) Apenas militares da patente Cabo+ podem comprar armamentos e sair da base;",
    "VIII-) Caso não cumpra com alguma punição solicitada, será exilado(a) imediatamente do Exército Brasileiro;",
    "IX-) Sempre utilize pronomes com os superiores (ex: Senhor ou Senhora);",
    "X-) Não é permitido perguntar ou pedir treinamentos e exames, caso contrário, será punido(a);",
    "XI-) Não treine em locais que estejam ocorrendo treinamentos, exames ou instruções;",
    "XII-) É extremamente proibido perguntas pessoais, caso faça, será punido(a);",
    "XIII-) É obrigatório utilizar o fardamento correto. Caso seja 'VIP', poderá personalizar com um tema militar.",
    "Alguma dúvida?",
    "Comandos de resposta:",
    "DIREI TA VOLVER ! - Você deve-se virar à sua direita;",
    "ESQUER DA VOLVER ! - Você deve-se virar à sua esquerda;",
    "RETA GUAR DA VOLVER ! - Você deve-se virar ao lado inverso da sua posição;",
    "VAN GUAR DA VOLVER ! - Você deve-se virar à posição inicial em que estava.",
    "Alguma dúvida?",
    "Formações:",
    "FORMAÇÃO ! - Você deverá ficar nesta linha cinza/branca, em posição ombro à ombro;",
    "FILA ÚNICA ! - Você deverá realizar uma fila única atrás do seu instrutor (mantenha o espaço de uma pessoa);",
    "CUNHA ! - Você deverá realizar uma formação em formato de V, atrás do seu instrutor.",
    "Alguma dúvida?",
    "Marchas:",
    "PREPARAR PARA MARCHAR ! - Você deverá aguardar o próximo comando do instrutor;",
    "MARCHEM ! - Você deverá marchar atrás do seu instrutor (sem ultrapassar os colegas ou correr);",
    "AUTO ! - Você deverá parar de marchar.",
    "Alguma dúvida?",
    "Comunicações:",
    "CONTINÊNCIA ! - Preste continência;",
    "Á VONTADE ! - Retire seu comando de mão, podendo mover-se;",
    "DESCANSAR ! - Coloque a mão para trás;",
    "SENTIDO ! - Retire qualquer comando de mão e fique imóvel;",
    "PPF ! - Permissão para falar;",
    "PPA ! - Permissão para assistir ou auxiliar;",
    "PPS ! - Permissão para sair.",
    "Alguma dúvida?",
    "Comandos falsos:",
    "Os comandos falsos são reconhecidos devido aos erros gramaticais ou letras em falta.",
    "ESQUERDA V0LVER !, FILA UNICA e assim vai...",
    "Jumping Jacks / Polichinelos (JJ's):",
    "Os Jumping Jacks (JJ's) fazem parte de treinamentos e também podem ser aplicados em militares que cometem infrações;",
    "Eles devem ser escritos utilizando CAPS LOCK e '!' no final.",
    "Deverão ser realizados conforme a quantidade solicitada pelo instrutor, e para ativá-los, basta apertar no botão com o símbolo de polichinelo na parte superior.",
    "Exemplo:",
    "ZERO !",
    "UM !",
    "DOIS !",
    "TRÊS !",
    "Assim vai...",
    "Alguma dúvida?",
    "Capacitação de Patente (CDP):",
    "A capacitação de patente (CDP) é a meta necessária para um militar ser promovido, podendo ser em dias e também com suas funções.",
    "Vale ressaltar que os militares que possuem a passe 'VIP', têm a CDP reduzida e conseguem ser promovidos mais rapidamente.",
    "Alguma dúvida?"
}